use susmitha;

-- DCL------- 
CREATE USER 'historian_user'@'%'
IDENTIFIED BY 'StrongP@ssw0rd';
GRANT SELECT ON susmitha.* TO 'historian_user'@'%';
FLUSH PRIVILEGES;

CREATE USER 'dynastyy_editor'@'local host' IDENTIFIED BY 'dynasty';
GRANT INSERT,UPDATE ON KINGS TO 'dynastyy_editor'@'local host';

CREATE USER 'booking_managre'@'local host' IDENTIFIED BY 'manager';
GRANT DELETE,UPDATE ON BOOKINGS TO 'booking_managre'@'local host';

CREATE USER 'enginer_team'@'local host' IDENTIFIED BY 'engineer';
GRANT DELETE,UPDATE ON SPACECRAFTS TO 'enginer_team'@'local host';
REVOKE DELETE ON SPACECRAFTS FROM 'enginer_team'@'local host';

CREATE USER 'chief_explorer'@'local host' IDENTIFIED BY 'chief';
GRANT ALL PRIVILEGES ON UIVERSES TO 'chief_explorer'@'local host' WITH GRANT OPTION;

CREATE ROLE astro_admin;
GRANT SELECT,INSERT,UPDATE ON SPACECRAFTS TO astro_admin;
GRANT SELECT,INSERT,UPDATE ON BOOKINGS TO astro_admin;

CREATE USER 'finance_team'@'local host' IDENTIFIED BY 'finance';
GRANT UPDATE(TICKET_PRICE) ON BOOKINGS TO 'finance_team'@'local host';
REVOKE UPDATE(TICKET_PRICE) ON BOOKINGS FROM 'finance_team'@'local host';

CREATE USER 'guest_user'@'local host' IDENTIFIED BY 'guest';
GRANT SELECT (KING_NAME,DYNASTY) ON KINGS TO 'guest_user'@'local host';


-- TCL--------
 START TRANSACTION;
 INSERT INTO BOOKINGS(BOOKING_ID,KING_ID,CRAFT_ID,UNIVERSE_ID,BOOKING_DATE,TRAVEL_DATE,TICKET_PRICE)
 VALUES(101,1,5,3,'2025-10-22','2025-12-01',5000);
 ROLLBACK;
 
 START TRANSACTION;
 UPDATE BOOKINGS SET TICKET_PRICE=TICKET_PRICE*0.10 WHERE BOOKING_ID=5;
 COMMIT;
 
 START TRANSACTION;
 UPDATE UIVERSES SET DANGER_LEVEL=50 WHERE UNIVERSE_ID=1;
 SAVEPOINT S1;
 ROLLBACK TO S1;
 COMMIT;
 
 START TRANSACTION;
 INSERT INTO SPACECRAFTS VALUES(201,'NEWCRAFT',100,5);
 ROLLBACK;
START TRANSACTION;
 -- DELETE FROM BOOKINGS WHERE ;
 
 
 
 START TRANSACTION;
 UPDATE SPACECRAFTS SET SPEED_LIGHT_YEAR=SPEED_LIGHT_YEAR+1 WHERE CRAFT_ID=3;
 INSERT INTO SPACECRAFTS VALUES(202,'EXPLORER',50,10);
 COMMIT;
 
 -- SET TRANSACTION READ ONLY;
 -- SELECT DYNASTY,AVG(TICKET_PRICE) FROM BOOKINGS GROUP BY DYNASTY;
 
 START TRANSACTION;
 UPDATE BOOKINGS SET TICKET_PRICE=TICKET_PRICE*1.05 WHERE UNIVERSE_ID=1;
 SAVEPOINT S1;
 UPDATE BOOKINGS SET TICKET_PRICE=TICKET_PRICE*1.10 WHERE UNIVERSE_ID=2;
 SAVEPOINT S2;
 ROLLBACK TO S1;
 COMMIT;
 


