-- VIEWS OF KINGS WHO MADE BOOKINGS IN 2025 
CREATE VIEW KINGS_2025 AS
SELECT K.* FROM KING K JOIN BOOKING B ON K.KING_ID=B.KING_ID WHERE B.BOOKING_DATE>=2025;
SELECT * FROM KINGS_2025;

-- VIEWS OF SPACECRAFTS WITH SPEED>80 LIGHTYEARS
CREATE VIEW FAST_CRAFTS AS
SELECT CARFT_NAME,SPEED_LIGHT_YEAR,CAPACITY FROM SPACECRAFT WHERE SPEED_LIGHT_YEAR>80;
SELECT * FROM FAST_CRAFTS;

-- VIEWS SHOWING KING NAME,DYNASTY AND UNIVERSE NAME FOR BOOKINGS WHERE DANGER LEVEL IS HIGH 
CREATE VIEW HIGH_DANGER_BOOKINGS AS
SELECT K.KING_NAME,K.DYNASTY,U.UNIVERSE_NAME FROM KING K
JOIN BOOKING B ON K.KING_ID=B.KING_ID JOIN UNIVERSES U ON B.UNIVERSE_ID=U.UNIVERSE_ID
WHERE U.DANGER_LEVEL>5;
SELECT * FROM HIGH_DANGER_BOOKINGS;

-- VIEW LISTING UNIVERSES AND NUMBER OF BOOKINGS FOR EACH
CREATE VIEW UNIVERSE_BOOKING_COUNT AS
SELECT U.UNIVERSE_NAME,COUNT(B.BOOKING_ID)FROM UNIVERSES U 
LEFT JOIN BOOKING B ON U.UNIVERSE_ID=B.UNIVERSE_ID
GROUP BY U.UNIVERSE_NAME;
SELECT * FROM UNIVERSE_BOOKING_COUNT;

-- VIEW OF KING NAMES AND TOTAL TICKET PRICE FOR BOOKINGS TO ANDROMEDA GALAXY
CREATE VIEW ANDROMEDA_TOTAL AS 
SELECT K.KING_NAME, SUM(B.TICKET_PRICE) AS TOTAL_PRICE FROM KING k
JOIN BOOKING B ON K.KING_ID=B.KING_ID
JOIN UNIVERSES U ON B.UNIVERSE_ID=U.UNIVERSE_ID
WHERE U.GALAXY_NAME='ANDROMEDA'
GROUP BY K.KING_NAME;
SELECT * FROM ANDROMEDA_TOTAL;


 --      TRIGGER
 
-- DEFAULT TICKET PRICE TRIGGER
CREATE TRIGGER SET_TICKETPRICE_DEFAULT BEFORE INSERT ON BOOKING
FOR EACH ROW 
WHEN(NEW.TICKET_PRICE IS NULL) 
BEGIN 
	:NEW.TICKET_PRICE:=5000; 
END;